# Site settings
title: CPSC 581 Projects
author: Benjamin Niles
description: "Benjamin Niles- Projects for CPSC 581 Fall 2023"

# Build settings
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme
