# Site settings
title: CPSC 581
author: Benjamin Niles
description: "Projects page"

# Build settings
theme: minima

navbar-links:
  -Projects:
    -title: Project 1
    url: "https://habitual-noiseless-trombone.glitch.me/"
    -title: Project 2
    url: "project2.html"

copyright: "Copyright (c){currentYear} {author}"
