# Site settings
title: CPSC 581
author:
  name: Benjamin Niles
description: "Projects page for CPSC 581 class"

# Build settings
theme: minima

navbar-links:
  Projects:
    -Project 1: "https://habitual-noiseless-trombone.glitch.me/"
    -Project 2: "project2.html"

copyright: "Copyright (c){currentYear} {author}"
